// <auto-generated />
using fastmusic.DataProviders;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace fastmusic.Migrations
{
    [DbContext(typeof(MusicProvider))]
    [Migration("20171115110417_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("fastmusic.DataProviders.MusicProvider+DbUpdateTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("LastUpdateTime");
                });

            modelBuilder.Entity("fastmusic.DataTypes.DbTrack", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Album");

                    b.Property<string>("AlbumArtist");

                    b.Property<string>("FileName");

                    b.Property<string>("Performer");

                    b.Property<string>("Title");

                    b.Property<uint>("TrackNumber");

                    b.Property<uint>("Year");

                    b.HasKey("Id");

                    b.ToTable("AllTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
